site_name: GenomeScript Documentation
site_description: Documentation for the GenomeScript genomic analysis language
repo_url: https://github.com/genomescript/genomescript
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - def_list
  - tables

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Basic Concepts: getting-started/concepts.md
  - User Guide:
    - Language Reference: user-guide/language-reference.md
    - Genomic Operations: user-guide/genomic-operations.md
    - AI Features: user-guide/ai-features.md
    - Blockchain Integration: user-guide/blockchain.md
  - API Reference:
    - Compiler: api/compiler.md
    - VM: api/vm.md
    - Genomics: api/genomics.md
    - AI: api/ai.md
    - Blockchain: api/blockchain.md
  - Contributing:
    - Development Setup: contributing/development.md
    - Code Style: contributing/code-style.md
    - Testing: contributing/testing.md 