name: Deploy GenomeScript

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine pytest pytest-cov
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python -m pytest tests/genomics/ -v --cov=src/genomics
          
      - name: Build package
        run: |
          python -m build
          
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          python -m twine upload --repository-url https://maven.pkg.github.com/nucleumdna/GenomeScript dist/* -u nucleumdna -p ${GITHUB_TOKEN}
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: .github/RELEASE_TEMPLATE.md
          owner: nucleumdna
          repo: GenomeScript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}