name: Genomics CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/genomics/**'
      - 'tests/genomics/**'
      - 'docs/**'
      - 'setup.py'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/genomics/**'
      - 'tests/genomics/**'
      - 'docs/**'
      - 'setup.py'
      - 'CHANGELOG.md'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pysam numpy biopython
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        python -m pytest tests/genomics/ -v --cov=src/genomics 